USE [AAD]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='tmp_t_location_mssql_2741')
   DROP TABLE tmp_t_location_mssql_2741;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='tmp_t_location_mssql_2741b')
   DROP TABLE tmp_t_location_mssql_2741b;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='tmp_t_zone_loca_mssql_2741')
   DROP TABLE tmp_t_zone_loca_mssql_2741;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='tmp_t_class_loca_mssql_2741')
   DROP TABLE tmp_t_class_loca_mssql_2741;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='tmp_t_zone_mssql_2741')
   DROP TABLE tmp_t_zone_mssql_2741;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='tmp_t_pick_area_mssql_2741')
   DROP TABLE tmp_t_pick_area_mssql_2741;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='tmp_t_class_mssql_2741')
   DROP TABLE tmp_t_class_mssql_2741;