USE AAD

DECLARE @order_number as nvarchar(30)
SET @order_number = '61a541a11a2f000013dbe96e'

--This runs forever, do not use!
----check that everything lines up between tables
--SELECT DISTINCT 'orphan check' as [test]
--	, od.item_number [t_order_detail.item_number]
--	, pkd.item_number [t_pick_detail.item_number]
----	, fwp.item_number [t_fwd_pick.item_number]
--FROM t_order_detail od
--FULL JOIN t_pick_detail pkd on od.item_number = pkd.item_number
----FULL JOIN t_fwd_pick fwp on od.item_number = fwp.item_number
--WHERE od.order_number = @order_number
--	OR pkd.order_number = @order_number

--TODO: check that picks are not in multiple carts at the same time

SELECT DISTINCT 't_message_log_inbound' [t_message_log_inbound]
	  ,[unique_id]
      ,[import_message]
      ,[date_inserted]
      ,[response]
      ,[date_processed]
      ,[message_id]
      ,[message_type]
      ,[environment]
  FROM [dbo].[t_message_log_inbound]
  WHERE message_type IN ('HOST_ORD_ROUTE_IMPORT', 'HOST_ORDER_IMPORT')
	AND JSON_VALUE(import_message, '$.Message.Contents.Orders[0].OrderMaster.order_number') = @order_number
  ORDER BY date_inserted desc


SELECT 't_order' as [t_order]
      ,[status]
      ,[route]
      ,[cutoff_date_time]
--we care about the stuff above ^
--the stuff below not so much v
      ,[order_id]
      ,[wh_id]
      ,[order_number]
      ,[store_order_number]
      ,[type_id]
      ,[customer_id]
      ,[cust_po_number]
      ,[customer_name]
      ,[customer_phone]
      ,[customer_fax]
      ,[customer_email]
      ,[department]
      ,[load_id]
      ,[load_seq]
      ,[bol_number]
      ,[pro_number]
      ,[master_bol_number]
      ,[carrier]
      ,[carrier_scac]
      ,[freight_terms]
      ,[rush]
      ,[priority]
      ,[order_date]
      ,[arrive_date]
      ,[actual_arrival_date]
      ,[date_picked]
      ,[date_expected]
      ,[promised_date]
      ,[weight]
      ,[cubic_volume]
      ,[containers]
      ,[backorder]
      ,[pre_paid]
      ,[cod_amount]
      ,[insurance_amount]
      ,[pip_amount]
      ,[freight_cost]
      ,[region]
      ,[bill_to_code]
      ,[bill_to_name]
      ,[bill_to_addr1]
      ,[bill_to_addr2]
      ,[bill_to_addr3]
      ,[bill_to_city]
      ,[bill_to_state]
      ,[bill_to_zip]
      ,[bill_to_country_code]
      ,[bill_to_country_name]
      ,[bill_to_phone]
      ,[ship_to_code]
      ,[ship_to_name]
      ,[ship_to_addr1]
      ,[ship_to_addr2]
      ,[ship_to_addr3]
      ,[ship_to_city]
      ,[ship_to_state]
      ,[ship_to_zip]
      ,[ship_to_country_code]
      ,[ship_to_country_name]
      ,[ship_to_phone]
      ,[ship_to_ein]
      ,[delivery_name]
      ,[delivery_addr1]
      ,[delivery_addr2]
      ,[delivery_addr3]
      ,[delivery_city]
      ,[delivery_state]
      ,[delivery_zip]
      ,[delivery_country_code]
      ,[delivery_country_name]
      ,[delivery_phone]
      ,[bill_frght_to_code]
      ,[bill_frght_to_name]
      ,[bill_frght_to_addr1]
      ,[bill_frght_to_addr2]
      ,[bill_frght_to_addr3]
      ,[bill_frght_to_city]
      ,[bill_frght_to_state]
      ,[bill_frght_to_zip]
      ,[bill_frght_to_country_code]
      ,[bill_frght_to_country_name]
      ,[bill_frght_to_phone]
      ,[return_to_code]
      ,[return_to_name]
      ,[return_to_addr1]
      ,[return_to_addr2]
      ,[return_to_addr3]
      ,[return_to_city]
      ,[return_to_state]
      ,[return_to_zip]
      ,[return_to_country_code]
      ,[return_to_country_name]
      ,[return_to_phone]
      ,[appointment_number]
      ,[appointment_status]
      ,[scheduled_location]
      ,[scheduled_start]
      ,[scheduled_duration]
      ,[rma_number]
      ,[rma_expiration_date]
      ,[carton_label]
      ,[ver_flag]
      ,[full_pallets]
      ,[haz_flag]
      ,[order_wgt]
      ,[zone]
      ,[drop_ship]
      ,[lock_flag]
      ,[partial_order_flag]
      ,[earliest_ship_date]
      ,[latest_ship_date]
      ,[actual_ship_date]
      ,[earliest_delivery_date]
      ,[latest_delivery_date]
      ,[actual_delivery_date]
      ,[baseline_rate]
      ,[planning_rate]
      ,[carrier_id]
      ,[manifest_carrier_id]
      ,[ship_via_id]
      ,[display_order_number]
      ,[client_code]
      ,[ship_to_residential_flag]
      ,[carrier_mode]
      ,[service_level]
      ,[ship_to_attention]
      ,[earliest_appt_time]
      ,[latest_appt_time]
      ,[image_entity_item_id]
      ,[order_type]
      ,[updated_date_time]
      ,[is_gift]
      ,[gift_recipient_name]
      ,[customer_first_name]
      ,[customer_last_name]
      ,[host_status]
      ,[error_msg]
      ,[cartonization_job_id]
      ,[release_relpen_date]
      ,[release_prep_date]
      ,[release_pick_date]
      ,[is_will_call]
      ,[retry_cartonize]
      ,[retry_cartonize_datetime]
  FROM [dbo].[t_order]
WHERE order_number = @order_number

select 't_order_detail' as [t_order_detail]
	, *
from t_order_detail
where order_number = @order_number

SELECT DISTINCT 't_pick_container' [t_pick_container]
	  ,[container_id]
      ,[t_pick_container].[wh_id]
      ,[container_type]
      ,[user_assigned]
      ,[t_pick_container].[order_number]
      ,[t_pick_container].[status]
      ,[container_label]
      ,[label_status]
      ,[cartonization_batch_id]
      ,[manifest_status]
      ,[tracking_number]
      ,[actual_length]
      ,[actual_width]
      ,[actual_height]
      ,[actual_weight]
      ,[carrier_id]
      ,[manifest_carrier_id]
      ,[ship_via_id]
      ,[sat_delivery_flag]
      ,[registered_mail_flag]
      ,[restricted_mail_flag]
      ,[freight_cost]
      ,[insurance_flag]
      ,[insured_amount]
      ,[target_ship_date]
      ,[actual_ship_date]
      ,[shipment_id]
      ,[print_sequence]
      ,[print_data]
      ,[bol_number]
      ,[create_date]
      ,[is_vas_verified]
      ,[label_print_date]
      ,[requires_audit]
      ,[is_override_exception]
      ,[box_sequence]
  FROM [dbo].[t_pick_container]
WHERE order_number = @order_number

SELECT 't_pick_detail' as [t_pick_detail] --reorder columns as needed 
      ,[status]
      ,[item_number]
      ,[container_id]
      ,[sub_container_id]
      ,[user_assigned]
--we care about the stuff above ^
--the stuff below not so much, maybe later. Comment it out for now v
	  ,[pick_id]
      ,[order_number]
      ,[line_number]
      ,[type]
      ,[uom]
      ,[work_q_id]
      ,[work_type]
      ,[lot_number]
      ,[unplanned_quantity]
      ,[planned_quantity]
      ,[picked_quantity]
      ,[staged_quantity]
      ,[loaded_quantity]
      ,[packed_quantity]
      ,[shipped_quantity]
      ,[staging_location]
      ,[zone]
      ,[wave_id]
      ,[load_id]
      ,[load_sequence]
      ,[stop_id]
      ,[pick_category]
      ,[bulk_pick_flag]
      ,[stacking_sequence]
      ,[pick_area]
      ,[wh_id]
      ,[cartonization_batch_id]
      ,[manifest_batch_id]
      ,[stored_attribute_id]
      ,[create_date]
      ,[before_pick_rule]
      ,[during_pick_rule]
      ,[hold_reason_id]
      ,[pick_run]
      ,[pick_loc_exp_date]
      ,[pick_location]
      ,[priority]
      ,[container_type]
      ,[previous_pick_id]
      ,[pick_datetime]
      ,[pick_loc_change_datetime]
      ,[inserted_datetime]
      ,[cartonization_pick_id]
      ,[rls_prep_date]
      ,[rls_rpln_date]
      ,[rls_pick_date]
      ,[zone_pick_type]
  FROM [dbo].[t_pick_detail]
where order_number = @order_number
ORDER BY status

SELECT DISTINCT 't_hu_master' as [t_hu_master]
	  ,[hu_id]
      ,t_hu_master.[type]
      ,[parent_hu_id]
--we care about the stuff above ^
--the stuff below not so much, maybe later. Comment it out for now v
      ,[control_number]
      ,[location_id]
      ,[subtype]
      ,t_hu_master.[status]
      ,[fifo_date]
      ,t_hu_master.[wh_id]
      ,[load_position]
      ,[haz_material]
      ,t_hu_master.[load_id]
      ,[load_seq]
      ,[ver_flag]
      ,t_hu_master.[zone]
      ,[reserved_for]
      ,t_hu_master.[container_type]
      ,t_hu_master.[stop_id]
      ,[parent_hu_id]
      ,[user_id]
      ,[dwell_start]
      ,[sell_by_date]
      ,[length]
      ,[width]
      ,[height]
      ,[box_type]
      ,[po_number]
      ,[po_line_number]
      ,[ice_flag]
      ,[last_qa_check]
      ,[qa_check_needed]
      ,[last_tran_date]
      ,[last_cc_date]
  FROM [dbo].[t_hu_master]
JOIN t_pick_detail ON t_hu_master.hu_id = t_pick_detail.container_id
WHERE control_number = @order_number

SELECT DISTINCT 't_route_detail' [t_route_detail]
	  ,[t_route_detail].[wh_id]
      ,[t_route_detail].[route_id]
      ,[order_number]
      ,[stop_sequence]
      ,[scheduled_arrival_date_time]
      ,[t_route_detail].[inserted_date]
      ,[pending_subcartonization]
  FROM [dbo].[t_route_detail]
  JOIN t_route_master on [t_route_detail].route_id = t_route_master.route_id
WHERE order_number = @order_number

SELECT DISTINCT 't_item_master' AS [t_item_master]
	  , t_item_master.*
from t_item_master
join t_order_detail on t_item_master.item_number = t_order_detail.item_number
and t_item_master.wh_id = t_order_detail.wh_id
where order_number = @order_number

select distinct 't_stored_item' as [t_stored_item]
	, t_stored_item.*
from t_stored_item
join t_order_detail on t_stored_item.item_number = t_order_detail.item_number
and t_stored_item.wh_id = t_order_detail.wh_id
where order_number = @order_number
--and t_stored_item.item_number = '5e200788241e04000e25e9af'

SELECT distinct 't_location' as [t_location]
      ,[pick_area]
--we care about the stuff above ^
--the stuff below not so much v
	  ,t_location.[wh_id]
      ,t_location.[location_id]
      ,[description]
      ,[short_location_id]
      ,t_location.[status]
      ,[zone]
      ,t_location.[picking_flow]
      ,[capacity_uom]
      ,[capacity_qty]
      ,[stored_qty]
      ,t_location.[type]
      ,t_location.[fifo_date]
      ,[cycle_count_class]
      ,[last_count_date]
      ,[last_physical_date]
      ,[user_count]
      ,[capacity_volume]
      ,[time_between_maintenance]
      ,[last_maintained]
      ,[length]
      ,[width]
      ,[height]
      ,[replenishment_location_id]
      ,[allow_bulk_pick]
      ,[slot_rank]
      ,[slot_status]
      ,[item_hu_indicator]
      ,[c1]
      ,[c2]
      ,[c3]
      ,[random_cc]
      ,[x_coordinate]
      ,[y_coordinate]
      ,[z_coordinate]
      ,[storage_device_id]
      ,[equipment_type]
      ,[location_group]
      ,[is_pallet_controlled]
      ,[pick_put_seq]
      ,[dynamic_flag]
      ,[sub_type]
      ,[aisle]
      ,[bay]
      ,[sub_bay]
      ,[position]
      ,[shelf]
      ,[check_digit]
      ,[inserted_date]
      ,[stage_replen]
      ,[match_sequence]
      ,[updated_by]
      ,[updated_from]
  FROM [dbo].[t_location]
JOIN t_stored_item ON t_location.location_id = t_stored_item.location_id
JOIN t_order_detail ON t_stored_item.item_number = t_order_detail.item_number
AND t_location.wh_id = t_order_detail.wh_id
WHERE order_number = @order_number
--and t_stored_item.item_number = '5e200788241e04000e25e9af'

--select --od.order_number, od.qty 
--sum(od.qty)
--from t_order_detail od
--join t_order o on od.order_number = o.order_number
--where item_number  = '5e2007f934b2e3000ef4e5cd'
--and o.status <> 'SHIPPED'

--select *
--from t_pick_detail
--where item_number = '5f88a59a20d8fa0013b7e07b'
--and order_number = @order_number

SELECT 't_tran_log' as [t_tran_log]
      ,[description]
      ,[source_hu_id]
      ,[destination_hu_id]
      ,[source_location_id]
      ,[destination_location_id]
      ,[start_tran_date]
      ,[start_tran_time]
      ,[calling_procedure]
--we care about the stuff above ^
--the stuff below not so much v
	  ,[tran_log_id]
      ,[tran_type]
      ,[end_tran_date]
      ,[end_tran_time]
      ,[employee_id]
      ,[line_number]
      ,[outside_id]
      ,[wh_id]
      ,[num_items]
      ,[item_number]
      ,[lot_number]
      ,[uom]
      ,[tran_qty]
      ,[verify_status]
      ,[employee_id_2]
      ,[routing_code]
      ,[return_disposition]
      ,[elapsed_time]
      ,[source_storage_type]
      ,[destination_storage_type]
      ,[generic_text1]
      ,[generic_text2]
      ,[generic_text3]
      ,[generic_text4]
      ,[generic_text5]
      ,[generic_float1]
      ,[generic_float2]
      ,[display_item_number]
      ,[client_code]
      ,[trk_summary_id]
      ,[tran_log_holding_id]
      ,[work_q_id]
      ,[outbound_order_number]
      ,[inbound_order_number]
      ,[receipt_id]
      ,[pick_id]
      ,[tran_group_id]
      ,[wave_id]
      ,[load_id]
      ,[expiration_date]
      ,[destination_wh_id]
      ,[shipment_id]
      ,[actual_carrier]
      ,[asn_number]
      ,[reason_code]
      ,[service_level]
      ,[customer]
      ,[control_number]
      ,[container_number]
      ,[group_id]
      ,[kit_id]
      ,[kit_lot_number]
      ,[loc_status]
      ,[loc_status2]
      ,[tracking_number]
      ,[release_holds]
      ,[misc_id]
      ,[source_parent_hu_id]
      ,[destination_parent_hu_id]
      ,[temperature]
      ,[destination_item_number]
      ,[destination_tran_qty]
      ,[sys_device]
      ,[inbound_order_line]
      ,[outbound_order_line]
      ,[outbound_order_number2]
      ,[work_type]
      ,[temp_name]
      ,[temp_name_2]
  FROM [dbo].[t_tran_log]
WHERE outbound_order_number = @order_number
--and (source_hu_id = '000000000000000006VL86'
--	or destination_hu_id = '000000000000000006VL86')
order by start_tran_date, start_tran_time

SELECT 't_error_log' AS [t_error_log]
	  ,[error_log_id]
      ,[error_number]
      ,[error_severity]
      ,[error_state]
      ,[error_procedure]
      ,[error_line]
      ,[error_message]
      ,[username]
      ,[type]
      ,[call_string]
      ,[calling_procedure]
      ,[create_date]
  FROM [dbo].[t_error_log]
WHERE error_message LIKE '%' + @order_number + '%'

--done with main database, now we search the archives
SELECT *
FROM AAD_ARCHIVE.dbo.t_order AS [orm] 
WHERE orm.order_number = @order_number

SELECT *
FROM AAD_ARCHIVE.dbo.t_route_detail AS [rd] 
WHERE rd.order_number = @order_number

SELECT DISTINCT rm.*
FROM AAD_ARCHIVE.dbo.t_route_master AS [rm] 
JOIN AAD_ARCHIVE.dbo.t_route_detail AS [rd] 
	ON rm.route_id = rd.route_id
WHERE rd.order_number = @order_number
